In [2]:
import mido
import numpy as np
from mido import MidiFile

mid = MidiFile('midis/Blues_Licks_-_Claus_Winther_Style_Solo.mid')

FileNotFoundError: [Errno 2] No such file or directory: 'midis/Blues_Licks_-_Claus_Winther_Style_Solo.mid'

In [6]:
i = 0
data = np.tile(0,(100,16))
bar = 0
pitch =0
note_on = 0
for j, track in enumerate(mid.tracks):
        for msg in track:
            bar = math.floor(round(i)/16)

            if note_on:
                if msg.type == "pitchwheel":
                    pitch=pitch + msg.time

                if msg.type == "note_off":

                    for n in range(int(round(i)%16), int(round(i)%16+(msg.time+pitch)/240)):
                        if n<16:
                            data[bar][n]=msg.note
                        else:
                            data[bar+1][n-16] = msg.note
                    i=i+(msg.time+pitch)/240
                    pitch=0
                    note_on=0
            
            else:
                if msg.type == "note_on":
                    i = i+msg.time/240
                    pitch = 0
                    note_on=1
                elif msg.type == "pitchwheel":
                    i=i+msg.time/240

                
                

print(data[:50])
                

NameError: name 'mid' is not defined

In [7]:
i=0
newdata = np.tile(0,(70,16))

for bar in data:
    zero_els = np.count_nonzero(bar==0)
    if zero_els != 16:
        newdata[i] = bar
        i=i+1
        
print(newdata)   

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [ ]:
np.savetxt("data2.csv", data, delimiter=",")

In [ ]:
cleanedata = np.tile(0,(364,17,50))
i=0
for array in data:
    for j in range(0,16):
        if float(array[j])>0:
            note_id=int(float(array[j])-40)
            cleanedata[i][j][note_id]=1
            
            
    tune = array[16]
    if tune=='C':
        cleanedata[i][16][32]=1
        cleanedata[i][16][36]=1
        cleanedata[i][16][39]=1
    elif tune == 'F':
        cleanedata[i][16][37]=1
        cleanedata[i][16][41]=1
        cleanedata[i][16][44]=1
    elif tune == 'A':
        cleanedata[i][16][41]=1
        cleanedata[i][16][45]=1
        cleanedata[i][16][48]=1
    elif tune == 'Am':
        cleanedata[i][16][41]=1
        cleanedata[i][16][44]=1
        cleanedata[i][16][48]=1
    elif tune == 'D':
        cleanedata[i][16][34]=1
        cleanedata[i][16][38]=1
        cleanedata[i][16][41]=1
    elif tune == 'Dm':
        cleanedata[i][16][34]=1
        cleanedata[i][16][37]=1
        cleanedata[i][16][41]=1
    elif tune == 'E':
        cleanedata[i][16][36]=1
        cleanedata[i][16][40]=1
        cleanedata[i][16][43]=1
    elif tune == 'Em':
        cleanedata[i][16][36]=1
        cleanedata[i][16][39]=1
        cleanedata[i][16][43]=1
    elif tune == 'B':
        cleanedata[i][16][31]=1
        cleanedata[i][16][35]=1
        cleanedata[i][16][39]=1
    elif tune == 'Bm':
        cleanedata[i][16][31]=1
        cleanedata[i][16][34]=1
        cleanedata[i][16][39]=1
    i=i+1

print(cleanedata.shape)

In [ ]:
#transform (364,17,50) into (364,850)

def preprocess(x):
    ret = torch.Tensor(364,850).zero_()
    for i in range(0,364):
        for j in range(0,17):
            for k in range(0,50):
                ret[i][j*50+k]= int(x[i][j][k])
        
    return ret

In [3]:
data=np.loadtxt(open("data.csv", "rb"), delimiter=",", skiprows=0, dtype=str)


In [10]:
cleanedata = np.tile(0,(364,19))
i=0
for array in data:
    for j in range(0,16):
        if float(array[j])>0:
            note_id=int(float(array[j])-40)
            cleanedata[i][j]=note_id
            
            
    tune = array[16]
    if tune=='C':
        cleanedata[i][16]=20
        cleanedata[i][17]=24
        cleanedata[i][18]=27
    elif tune == 'F':
        cleanedata[i][16]=25
        cleanedata[i][17]=29
        cleanedata[i][18]=32
    elif tune == 'A':
        cleanedata[i][16]=29
        cleanedata[i][17]=33
        cleanedata[i][18]=36
    elif tune == 'Am':
        cleanedata[i][16]=29
        cleanedata[i][17]=32
        cleanedata[i][18]=36
    elif tune == 'D':
        cleanedata[i][16]=22
        cleanedata[i][17]=26
        cleanedata[i][18]=29
    elif tune == 'Dm':
        cleanedata[i][16]=22
        cleanedata[i][17]=25
        cleanedata[i][18]=29
    elif tune == 'E':
        cleanedata[i][16]=24
        cleanedata[i][17]=28
        cleanedata[i][18]=31
    elif tune == 'Em':
        cleanedata[i][16]=24
        cleanedata[i][17]=27
        cleanedata[i][18]=31
    elif tune == 'B':
        cleanedata[i][16]=19
        cleanedata[i][17]=23
        cleanedata[i][18]=26
    elif tune == 'Bm':
        cleanedata[i][16]=19
        cleanedata[i][17]=22
        cleanedata[i][18]=26
    i=i+1

print(cleanedata.shape)


(364, 19)


In [11]:
print(cleanedata[363])

[40 40 37 37 35 35 37 37 42 42 42 42 42 42 42 42 25 29 32]


In [15]:
shifted = np.tile(0,(4368,19))
for i in range(0,364):
    shifted[i]=cleanedata[i]

In [23]:
print(shifted[363])

[40 40 37 37 35 35 37 37 42 42 42 42 42 42 42 42 37 41 44]


In [16]:
i = 364
for bar in cleanedata:
    for shift in range(1,12):
        shifted[i]=(bar+shift)%50
        i=i+1

In [13]:
print(shifted[4000])

[39 36  7 31 39 36  7 31 39 36  7 31 34 34 36 36 36 40 43]


In [27]:
#normalisation -1 ; 1


-1.0

In [28]:
np.savetxt("extended.csv",shifted,delimiter=",")